service: serverless-demo

package:
  individually: true
  exclude:
    - bin/**
    - events/**
    - utils/**
    - .idea/**
    - .env
    - .env.sample
    - .eslintrc.js
    - "*.pdf"
    - "*.txt"
    - "*.md"
    - "package*.json"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 512
  timeout: 10

functions:
  simple:
    handler: src/handler.simple
    events:
      - http:
          path: simple
          method: get
